name: Update Study Count Badge

on:
  schedule:
    # Run every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-study-count:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install EDirect tools
      run: |
        # Install EDirect tools for esearch/efetch/xtract/transmute
        wget -O edirect.tar.gz "ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.tar.gz"
        tar -xzf edirect.tar.gz
        mv edirect $HOME/

        wget -O xtract.gz "ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/xtract.Linux.gz"
        gunzip -f xtract.gz
        chmod +x xtract
        mv xtract $HOME/edirect
        
        wget -O transmute.gz "ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/transmute.Linux.gz"
        gunzip -f transmute.gz
        chmod +x transmute
        mv transmute $HOME/edirect
        
        echo "$HOME/edirect" >> $GITHUB_PATH

    - name: Verify EDirect commands are available
      run: |
        set -euo pipefail
        echo "PATH: $PATH"
        for cmd in esearch efetch xtract transmute; do
          printf "Checking %s... " "$cmd"
          if ! command -v "$cmd" >/dev/null 2>&1; then
            echo "NOT FOUND" >&2
            echo "Error: $cmd not found on PATH after installation." >&2
            exit 1
          fi
          echo "OK ($(command -v "$cmd"))"
        done

    - name: Get study count and IDs
      id: count
      run: |
        set -euo pipefail
        # Run the esearch command to get unique study IDs
        STUDY_IDS=$(esearch -db sra -query '"q2-ena-uploader"[All Fields]' | \
          efetch -format xml | \
          xtract -pattern "STUDY_REF/*" -block IDENTIFIERS -element PRIMARY_ID)
        
        SAMPLE_COUNT=$(printf "%s\n" "$STUDY_IDS" | wc -l)
        STUDY_IDS=$(printf "%s\n" "$STUDY_IDS" | sort -u)
        
        # Count only non-empty lines to avoid counting a blank line as 1; use awk to avoid non-zero exit when empty
        STUDY_COUNT=$(printf "%s\n" "$STUDY_IDS" | awk 'NF{c++} END{print c+0}')
        
        echo "Study count: $STUDY_COUNT"
        echo "Sample count: $SAMPLE_COUNT"
        echo "Found study IDs:"
        echo "$STUDY_IDS"
        
        # Fail the workflow if the study count is empty or zero
        if [ -z "${STUDY_COUNT:-}" ] || [ "$STUDY_COUNT" -eq 0 ]; then
          echo "Error: No ENA studies found for query 'q2-ena-uploader'." 1>&2
          exit 1
        fi
        
        # Save outputs for later steps
        echo "study-count=$STUDY_COUNT" >> $GITHUB_OUTPUT
        echo "sample-count=$SAMPLE_COUNT" >> $GITHUB_OUTPUT
        echo "ids<<EOF" >> $GITHUB_OUTPUT
        echo "$STUDY_IDS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Determine if counts changed
      id: diff
      run: |
        set -euo pipefail
        NEW_STUDY="${{ steps.count.outputs.study-count }}"
        NEW_SAMPLE="${{ steps.count.outputs.sample-count }}"
        
        if [ ! -f "study-count-history.csv" ] || [ ! -s "study-count-history.csv" ]; then
          echo "No history CSV found; will create and commit new counts."
          echo "changed=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        LAST_LINE=$(tail -n 1 study-count-history.csv)
        # If the last line is the header or malformed, treat as changed
        if echo "$LAST_LINE" | grep -q '^date,study-count,sample-count$'; then
          echo "Last CSV line is header; treating as changed."
          echo "changed=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        LAST_STUDY=$(echo "$LAST_LINE" | awk -F, 'NF>=2 {print $2}')
        LAST_SAMPLE=$(echo "$LAST_LINE" | awk -F, 'NF>=3 {print $3}')
        
        if [ -z "$LAST_STUDY" ] || [ -z "$LAST_SAMPLE" ]; then
          echo "Last CSV line missing counts; treating as changed."
          echo "changed=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        if [ "$NEW_STUDY" != "$LAST_STUDY" ] || [ "$NEW_SAMPLE" != "$LAST_SAMPLE" ]; then
          echo "Counts changed: studies $LAST_STUDY -> $NEW_STUDY, samples $LAST_SAMPLE -> $NEW_SAMPLE"
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "Counts unchanged (studies=$NEW_STUDY, samples=$NEW_SAMPLE)."
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Update CSV tracking file
      if: steps.diff.outputs.changed == 'true'
      run: |
        # Current study count and date
        STUDY_COUNT="${{ steps.count.outputs.study-count }}"
        SAMPLE_COUNT="${{ steps.count.outputs.sample-count }}"
        CURRENT_DATE=$(date '+%Y-%m-%d')
        
        # Create CSV file if it doesn't exist
        if [ ! -f "study-count-history.csv" ]; then
          echo "date,study-count,sample-count" > study-count-history.csv
        fi
        
        # Add new entry to CSV
        echo "${CURRENT_DATE},${STUDY_COUNT},${SAMPLE_COUNT}" >> study-count-history.csv

    - name: Update README badge
      if: steps.diff.outputs.changed == 'true'
      run: |
        # Current study count
        STUDY_COUNT="${{ steps.count.outputs.study-count }}"
        SAMPLE_COUNT="${{ steps.count.outputs.sample-count }}"
        
        # Create badge URLs
        STUDY_BADGE_URL="https://img.shields.io/badge/ENA%20Studies-${STUDY_COUNT}-blue"
        STUDY_BADGE_MARKDOWN="![ENA Studies](${STUDY_BADGE_URL})"
        SAMPLE_BADGE_URL="https://img.shields.io/badge/ENA%20Samples-${SAMPLE_COUNT}-blue"
        SAMPLE_BADGE_MARKDOWN="![ENA Samples](${SAMPLE_BADGE_URL})"
        
        # Check if badges already exist in README
        if grep -q "!\[ENA Studies\]" README.md; then
          # Update existing badges
          sed -i "s|!\[ENA Studies\]([^)]*)|${STUDY_BADGE_MARKDOWN}|g" README.md
          sed -i "s|!\[ENA Samples\]([^)]*)|${SAMPLE_BADGE_MARKDOWN}|g" README.md
        else
          # Add new badge after the existing badges
          sed -i '/!\[Code style: black\]/a\'"${STUDY_BADGE_MARKDOWN}\n${SAMPLE_BADGE_MARKDOWN}" README.md
        fi

    - name: Commit and push changes
      if: steps.diff.outputs.changed == 'true'
      env:
        GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: |
        git config --local user.email "bokulich-lab@ethz.ch"
        git config --local user.name "BOTulich"

        git remote set-url origin https://${{ env.GH_TOKEN }}@github.com/bokulich-lab/q2-ena-uploader.git
        
        # Add both files to git
        git add README.md study-count-history.csv
        
        # Check if there are any changes to commit
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update ENA counts: studies=${{ steps.count.outputs.study-count }}, samples=${{ steps.count.outputs.sample-count }}"
          git push
        fi
